language: php

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_script :
  - composer install
  - mysql -e 'create database translations_test;'
  - mysql -e "use mysql; SET PASSWORD FOR 'travis'@'localhost' = PASSWORD('travis'); FLUSH PRIVILEGES;"
  - ./vendor/bin/ar_migrate -i

after_script:
  - CODECLIMATE_REPO_TOKEN="c0b16bb2db866436407181b65fc9371a2ee4ea3004038b62e2a1a083bb1a4479" vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

script:
  - ./vendor/bin/phpcs --warning-severity=6 --standard=PSR2 *.php src tests fixtures
  - phpunit

notifications:
  email:
    - matthew@baggett.me
  slack: thruio:m7cGYXmdz261AkGDfiRVBHmY
